# -*- coding: utf-8 -*-
"""Temperature_16032020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gjVYBTjjbTybQKgrRpcf8xrkDdkzpXYL

Line Token for Python Group: 5t3gYYQY0ORJmr7849i1Y55zJDaW3eaR4CSvM61WT74

Line Token for Waranya: BQU9XxrNL0DgBfgWy9nVEmGCmQvbYcUoRZp3AMl8zoI
"""

from urllib.request import urlopen as req
from bs4 import BeautifulSoup as soup
from pprint import pprint
from songline import Sendline

def Temperature(pvid):
  try:
    #1 URL
    url = 'https://www.tmd.go.th/province.php?id='+str(pvid)

    #2 Request URL
    webopen = req(url)
    page_html = webopen.read()
    webopen.close()

    #3 Convert page_html to Soup object
    data = soup(page_html,'html.parser')
    #print(data)

    #4 Find element (td:'strokeme')
    temp = data.findAll('td',{'class':'strokeme'})
    province = data.findAll('span',{'class':'title'})

    pv = province[0].text.replace(' ','')
    tp = temp[0].text

    #print('จังหวัด: {} อุณหภูมิ: {}'.format(pv,tp))
    print(f'ID: {pvid} จังหวัด: {pv} อุณหภูมิ: {tp}') #fstring python 3.6+
    text = 'จังหวัด: {} อุณหภูมิ: {}'.format(pv,tp)
    return text #ต้อง return ค่า เพื่อนำไปใช้ในโปรแกรมอื่นได้
  except:
    print('No Result')
    return 'No Result'

'''
for i in range(1,2):
  #print(str(i))
  Temperature(i)
'''

#token = 'BQU9XxrNL0DgBfgWy9nVEmGCmQvbYcUoRZp3AMl8zoI' #Waranya
token = '5t3gYYQY0ORJmr7849i1Y55zJDaW3eaR4CSvM61WT74' #Python Group
messenger = Sendline(token)

mypv = Temperature(2)
messenger.sendtext(mypv)

#function ดักจับ error

'''
try:
  print('HELLO')
  print(lungtu)
except:
    print('ERROR')
'''

try:
  print('HELLO')
  print(lungtu)
except Exception as e:
    print('ERROR', e)

from songline import Sendline

token = 'BQU9XxrNL0DgBfgWy9nVEmGCmQvbYcUoRZp3AMl8zoI'
messenger = Sendline(token)

'''
#send message
messenger.sendtext('Hello world')

#send sticker
messenger.sticker(1,1)

#send image
messenger.sendimage('https://img.pngio.com/python-logo-python-logo-png-268_300.png')
'''

!pip install songline